name: Build TAG (from main branch)

on:
  release:
    types:
      - created
    paths-ignore:
      - .github/workflows/**

jobs:
  call-build-tag:
#    environment: development
    uses: qiot-project/qiot-ubi-all-reusable-workflows/.github/workflows/module-build-deploy.yml@main
    # Use the "secrets" keyword to pass named secrets.
    secrets:
      ARTIFACTORY_HOSTNAME: ${{ secrets.ARTIFACTORY_HOSTNAME }}
      ARTIFACTORY_SNAPSHOT_REPO: ${{ secrets.ARTIFACTORY_SNAPSHOT_REPO }}
      ARTIFACTORY_RELEASE_REPO: ${{ secrets.ARTIFACTORY_RELEASE_REPO }}
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
    # Workflows that call reusable workflows in the same organization or enterprise
    #  can use the "inherit" keyword to implicitly pass the secrets.
      # secrets: inherit
